
  const grid = [
    {
      horizontal: [
        false,
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        false,
      ],
      vertical: [true, true, false, false, true, false, true, true, false, false],
    },
    {
      horizontal: [
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      vertical: [true, true, true, true, false, true, false, true, true, false],
    },
    {
      horizontal: [
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
      ],
      vertical: [true, true, false, true, true, false, true, true, false, false],
    },
    {
      horizontal: [
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        false,
      ],
      vertical: [true, true, true, false, true, false, false, false, true, false],
    },
    {
      horizontal: [
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
      ],
      vertical: [true, true, true, false, true, false, true, false, false, false],
    },
    {
      horizontal: [
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
      ],
      vertical: [true, true, true, true, true, true, false, true, false, false],
    },
    {
      horizontal: [
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
      ],
      vertical: [true, false, true, true, true, true, true, false, false, false],
    },
    {
      horizontal: [
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
      ],
      vertical: [
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
      ],
    },
    {
      horizontal: [
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
      ],
      vertical: [
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        false,
      ],
    },
    {
      horizontal: [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
      ],
      vertical: [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    },
  ];
  

  
  export const mazeModel = {
    maze_id: "002",
    numCols: 10,
    numRows: 10,
    grid: grid,
  };
  